apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-installer-config
  namespace: node-installer
data:
  install.sh: |
    #!/bin/bash

    # Update and install packages
    apt-get update
    apt-get install cowsay -y
    systemctl disable apt-daily-upgrade.timer
    systemctl mask apt-daily-upgrade.service
